---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list: 
      - recipe[hem::default]
    attributes:
  - name: environment
    run_list:
      - recipe[hem::default]
      - recipe[hem::environment]
    attributes:
